// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Mkc4GRWuTAsh7ZIDqA73unWT_bLc88I',
    appId: '1:287517614988:web:11218cd8f5e0af190aeca9',
    messagingSenderId: '287517614988',
    projectId: 'flutter-video-audio-chat-6174c',
    authDomain: 'flutter-video-audio-chat-6174c.firebaseapp.com',
    storageBucket: 'flutter-video-audio-chat-6174c.appspot.com',
    measurementId: 'G-76V5Y21FRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbWMbBf943I1a4WcI32MEZZ9xcce6IMCQ',
    appId: '1:287517614988:android:d173326ebbc6a3630aeca9',
    messagingSenderId: '287517614988',
    projectId: 'flutter-video-audio-chat-6174c',
    storageBucket: 'flutter-video-audio-chat-6174c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk9aq-jCQywBP3wiZBCfxz7A2MP_kttyc',
    appId: '1:287517614988:ios:4ec5bf0e8304d1670aeca9',
    messagingSenderId: '287517614988',
    projectId: 'flutter-video-audio-chat-6174c',
    storageBucket: 'flutter-video-audio-chat-6174c.appspot.com',
    iosBundleId: 'com.example.flutterVideoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk9aq-jCQywBP3wiZBCfxz7A2MP_kttyc',
    appId: '1:287517614988:ios:a6a5a8fec11548fa0aeca9',
    messagingSenderId: '287517614988',
    projectId: 'flutter-video-audio-chat-6174c',
    storageBucket: 'flutter-video-audio-chat-6174c.appspot.com',
    iosBundleId: 'com.example.flutterVideoChat.RunnerTests',
  );
}
